#!/bin/sh

awk '
  /^  "(theme|icon_theme)"[[:space:]]*:[[:space:]]*\{/ {
    in_local_theme = 1
  }

  in_local_theme && /^    "mode"[[:space:]]*:/ {
    next
  }

  in_local_theme && /^  \},?[[:space:]]*$/ {
    in_local_theme = 0
  }

  { print }
'
