onboarding = false
[theme]
name = "catppuccin"

[theme.custom]
accent = "#c6a0f6"
panel_bg = "#24273a"
green = "#a6da95"
yellow = "#eed49f"
red = "#ed8796"
blue = "#8aadf4"

[ui]
accent = "#c6a0f6"
agent_panel_sort = "spaces"
